url_login: "https://test-stand.gb.ru/gateway/login"
url_posts: "https://test-stand.gb.ru/api/posts"
url_reg: "http://restapi.adequateshop.com/api/authaccount/registration"
url_login_api: "http://restapi.adequateshop.com/api/authaccount/login"

login: "Sixth Sense"
password: "81c597107f"